language: csharp,scala
sudo: required
before_install:
  - sudo apt-get install xsltproc openjdk-8-jdk maven
script:
  - export MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
  - export JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
  - export NUNITCONSOLE="`pwd`/testrunner/NUnit.Console.3.0.0/tools/nunit3-console.exe"
  - cd ./build
  - ./build.sh
